- name: remove existing app location
  ansible.builtin.file:
    path: /app
    state: absent
  ignore_errors: true

- name: create app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: "download the {{ component }} code"
  ansible.builtin.unarchive:
    src: "https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ component }}-v2.zip"
    dest: /app
    remote_src: yes